sudo: required
dist: trusty
language: php

php:
  - '7.1'

install:
  - travis_retry composer install --no-interaction

before_script: # refactor this to separate .sh file
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./vendor/laravel/dusk/bin/chromedriver-linux &
  - cp .env.example .env
  - php artisan serve &

script:
  - php artisan dusk

